kind: pipeline
name: test
type: docker

steps:
  - name: test
    image: maven:3-jdk-11
    commands:
      - mvn verify -B
#  - name: deploy
#    image: maven:3-jdk-11
#    commands:
#      - gradle uploadArchives -PsytmNexusUser=$SYTM_NEXUS_USER -PsytmNexusPassword=$SYTM_NEXUS_PASSWORD
#    when:
#      branch:
#        - master
#      event:
#        exclude:
#          - pull_request

trigger:
  event:
    - push