kind: pipeline
name: test
type: docker

steps:
  - name: test
    image: maven:3-jdk-11
    commands:
      - mvn verify -B -ntp

trigger:
  event:
    - push
---
kind: pipeline
name: deploy
type: docker

steps:
  - name: create maven settings
    image: md5lukas/drone-mvn-settings
    settings:
      serverSecrets:
        from_secret: maven_server_secrets
  - name: deploy
    image: maven:3-jdk-11
    commands:
      - mvn clean deploy -B -ntp

trigger:
  branch:
    - master
  event:
    exclude:
      - pull_request