kind: pipeline
name: default
type: docker

steps:
  - name: test
    image: gradle:5.4.1
    commands:
      - gradle test
  - name: deploy
    image: gradle:5.4.1
    environment:
      SYTM_NEXUS_USER:
        from_secret: repo_username
      SYTM_NEXUS_PASSWORD:
        from_secret: repo_password
    commands:
      - gradle uploadArchives -PsytmNexusUser=$SYTM_NEXUS_USER -PsytmNexusPassword=$SYTM_NEXUS_PASSWORD

trigger:
  event:
    - push